kafka-pool: nav-dev
ingress: https://aap-saksinfo.intern.dev.nav.no

arenaoppslag:
  proxyBaseUrl: https://arenaoppslag.dev-fss-pub.nais.io
  scope: api://dev-fss.aap.arenaoppslag/.default
  host: arenaoppslag.dev-fss-pub.nais.io